### ISSUE TITLE
[Feature request] nftables support

### ISSUE THREAD

**Issue by cofob** [dis-works/diswall-rs#2]
# Problem
`iptables` is already obsolete and is no longer supplied with Debain 11, for example. It is worth adding support for `nftables` to keep up with the times.

**Comment by Revertron** [comment]
We plan to implement eBPF filtering. It will be more robust than `nftables`, I think.

**Comment by Revertron** [comment]
Added support for `nftables` in 0509bf696c5442ccf91cddaeaeb70de9560c85df
